package org.example;


//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OP_CO_MAY = 40;
  public static final int TIPOS_DATOS = 11;
  public static final int OP_LO_AND = 30;
  public static final int OP_LO_NOT = 32;
  public static final int OP_AR_SUM = 34;
  public static final int LLAVE_APER = 6;
  public static final int CORCHETE_APER = 9;
  public static final int INTEGER = 26;
  public static final int PAREN_APER = 4;
  public static final int FILTER = 3;
  public static final int IGUAL = 49;
  public static final int OP_FALSE = 46;
  public static final int OP_AR_POT = 36;
  public static final int OP_AR_RES = 37;
  public static final int WHILE_INICIO = 13;
  public static final int BEGIN = 51;
  public static final int OP_LO_OR = 31;
  public static final int GUION = 50;
  public static final int CONST_FLOAT = 23;
  public static final int ELSE_IF = 17;
  public static final int WHILE_FIN = 14;
  public static final int EOF = 0;
  public static final int ENDDECLARE = 48;
  public static final int OP_AR_RTO = 35;
  public static final int COMILLA = 53;
  public static final int OP_CO_DIS = 44;
  public static final int error = 1;
  public static final int COMA = 8;
  public static final int COMENTARIO = 54;
  public static final int OP_CO_IGU = 33;
  public static final int DECLARE = 47;
  public static final int OP_AR_DIV = 39;
  public static final int ASIGNACION = 29;
  public static final int FIN_LINEA = 28;
  public static final int IF_INICIO = 15;
  public static final int FOR_INICIO = 18;
  public static final int PUNTO = 27;
  public static final int LLAVE_CIER = 7;
  public static final int FOR_FIN = 19;
  public static final int IF_FIN = 16;
  public static final int OP_AR_MUL = 38;
  public static final int CORCHETE_CIER = 10;
  public static final int FLOAT = 24;
  public static final int OP_CO_MAY_IGU = 43;
  public static final int CONST_STRING = 22;
  public static final int PAREN_CIER = 5;
  public static final int END = 52;
  public static final int OP_CO_MEN = 41;
  public static final int STRING = 25;
  public static final int OP_CO_MEN_IGU = 42;
  public static final int FOR_MEDIO = 20;
  public static final int VAR = 12;
  public static final int PRINT = 2;
  public static final int CONST_INT = 21;
  public static final int OP_TRUE = 45;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PRINT",
  "FILTER",
  "PAREN_APER",
  "PAREN_CIER",
  "LLAVE_APER",
  "LLAVE_CIER",
  "COMA",
  "CORCHETE_APER",
  "CORCHETE_CIER",
  "TIPOS_DATOS",
  "VAR",
  "WHILE_INICIO",
  "WHILE_FIN",
  "IF_INICIO",
  "IF_FIN",
  "ELSE_IF",
  "FOR_INICIO",
  "FOR_FIN",
  "FOR_MEDIO",
  "CONST_INT",
  "CONST_STRING",
  "CONST_FLOAT",
  "FLOAT",
  "STRING",
  "INTEGER",
  "PUNTO",
  "FIN_LINEA",
  "ASIGNACION",
  "OP_LO_AND",
  "OP_LO_OR",
  "OP_LO_NOT",
  "OP_CO_IGU",
  "OP_AR_SUM",
  "OP_AR_RTO",
  "OP_AR_POT",
  "OP_AR_RES",
  "OP_AR_MUL",
  "OP_AR_DIV",
  "OP_CO_MAY",
  "OP_CO_MEN",
  "OP_CO_MEN_IGU",
  "OP_CO_MAY_IGU",
  "OP_CO_DIS",
  "OP_TRUE",
  "OP_FALSE",
  "DECLARE",
  "ENDDECLARE",
  "IGUAL",
  "GUION",
  "BEGIN",
  "END",
  "COMILLA",
  "COMENTARIO"
  };
}

